version: "1.40.{build}"

#vc140
os: Visual Studio 2015

configuration:
  - Debug
  - Release

init:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: msbuild /version

clone_folder: C:\projects\SubtitleDownloader

build:
  project: C:\projects\SubtitleDownloader\SubtitlesDownloader.sln
  parallel: true
  verbosity: normal

test: off
